<a href="https://colab.research.google.com/github/DeepPatel4505/DataScience/blob/main/LinearReg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [3]:
path = "/sample_data/california_housing"
df = pd.read_csv(path)
df.head(10)

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

In [ ]:
X = df["X"]
Y = df["Y"]
theta0 = 0.4
theta1 = 0.4
alpha = 0.01
m = len(df)

In [ ]:
y_cap = theta0 + theta1 * X
# y_cap
(y_cap - Y)

0   -0.2
1   -0.8
2   -1.4
dtype: float64

In [ ]:
J = ((y_cap - Y) ** 2).sum() / (2 * m)
J

np.float64(0.43999999999999995)

In [ ]:
deltaJ0 = (y_cap - Y).sum() / m
deltaJ1 = ((y_cap - Y) * X).sum() / m
deltaJ0 , deltaJ1

(np.float64(-0.7999999999999998), np.float64(-1.9999999999999998))

In [ ]:
t0 = theta0 - alpha * deltaJ0
t1 = theta1 - alpha * deltaJ1
t0 , t1

(np.float64(0.40800000000000003), np.float64(0.42000000000000004))

In [ ]:
data = pd.read_csv("Housing.csv")
data.sample(10)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
158,5495000,7980,3,1,1,yes,no,no,no,no,2,no,semi-furnished
416,3395000,3450,3,1,1,yes,no,yes,no,no,2,no,unfurnished
363,3710000,3584,2,1,1,yes,no,no,yes,no,0,no,semi-furnished
411,3430000,2145,3,1,3,yes,no,no,no,no,0,yes,furnished
198,4935000,5948,3,1,2,yes,no,no,no,yes,0,no,semi-furnished
490,2835000,4350,3,1,2,no,no,no,yes,no,1,no,unfurnished
23,8645000,4560,3,2,2,yes,yes,yes,no,yes,1,no,furnished
61,7070000,8880,2,1,1,yes,no,no,no,yes,1,no,semi-furnished
393,3500000,7424,3,1,1,no,no,no,no,no,0,no,unfurnished
471,3010000,3750,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [ ]:
X = data.drop(['price'],axis=1)
X = pd.DataFrame(X)

Y = data["price"]
X.sample(10)
#  airconditioning , basement , prefarea
X["furnishingstatus"].value_counts()
Y.sample(10)

544     1750000
68      6860000
171     5250000
196     4970000
5      10850000
256     4480000
102     6195000
163     5425000
27      8400000
400     3500000
Name: price, dtype: int64

In [ ]:

from sklearn.preprocessing import LabelEncoder,StandardScaler

le = LabelEncoder()
st = StandardScaler()
cols = ["furnishingstatus" , "prefarea" , "basement" , "airconditioning"]

for col in cols:
  X[col] = le.fit_transform(X[col])

X = X.drop(["mainroad","guestroom","hotwaterheating"],axis=1)

st.fit(X)
X_scaled= st.fit_transform(X)
# Y_scaled = st.tranform(Y)

X = pd.DataFrame(X_scaled,columns=X.columns)
X

,area,bedrooms,bathrooms,stories,basement,airconditioning,parking,prefarea,furnishingstatus
0,1.046726,1.403419,1.421812,1.378217,-0.734539,1.472618,1.517692,1.804941,-1.406286
1,1.757010,1.403419,5.405809,2.532024,-0.734539,1.472618,2.679409,-0.554035,-1.406286
2,2.218232,0.047278,1.421812,0.224410,1.361397,-0.679063,1.517692,1.804941,-0.091662
3,1.083624,1.403419,1.421812,0.224410,1.361397,1.472618,2.679409,1.804941,-1.406286
4,1.046726,1.403419,-0.570187,0.224410,1.361397,1.472618,1.517692,-0.554035,-1.406286
...,...,...,...,...,...,...,...,...,...
540,-0.991879,-1.308863,-0.570187,-0.929397,1.361397,-0.679063,1.517692,-0.554035,1.222962
541,-1.268613,0.047278,-0.570187,-0.929397,-0.734539,-0.679063,-0.805741,-0.554035,-0.091662
542,-0.705921,-1.308863,-0.570187,-0.929397,-0.734539,-0.679063,-0.805741,-0.554035,1.222962
543,-1.033389,0.047278,-0.570187,-0.929397,-0.734539,-0.679063,-0.805741,-0.554035,-1.406286
544,-0.599839,0.047278,-0.570187,0.224410,-0.734539,-0.679063,-0.805741,-0.554035,1.222962

In [ ]:
X.describe()

,area,bedrooms,bathrooms,stories,basement,airconditioning,parking,prefarea,furnishingstatus
count,5.450000e+02,5.450000e+02,5.450000e+02,5.450000e+02,5.450000e+02,5.450000e+02,545.000000,545.000000,5.450000e+02
mean,-1.564498e-16,-1.825247e-16,-2.607496e-17,-1.303748e-16,-7.822489e-17,-5.214993e-17,0.000000,0.000000,1.825247e-16
std,1.000919e+00,1.000919e+00,1.000919e+00,1.000919e+00,1.000919e+00,1.000919e+00,1.000919,1.000919,1.000919e+00
min,-1.614530e+00,-2.665004e+00,-5.701867e-01,-9.293967e-01,-7.345393e-01,-6.790626e-01,-0.805741,-0.554035,-1.406286e+00
25%,-7.151451e-01,-1.308863e+00,-5.701867e-01,-9.293967e-01,-7.345393e-01,-6.790626e-01,-0.805741,-0.554035,-1.406286e+00
50%,-2.539222e-01,4.727831e-02,-5.701867e-01,2.244101e-01,-7.345393e-01,-6.790626e-01,-0.805741,-0.554035,-9.166185e-02
75%,5.578300e-01,4.727831e-02,1.421812e+00,2.244101e-01,1.361397e+00,1.472618e+00,0.355976,-0.554035,1.222962e+00
max,5.096263e+00,4.115701e+00,5.405809e+00,2.532024e+00,1.361397e+00,1.472618e+00,2.679409,1.804941,1.222962e+00

In [ ]:
X["temp"] = 1
X.sample(10)

,area,bedrooms,bathrooms,stories,basement,airconditioning,parking,prefarea,furnishingstatus,temp
379,-0.752043,0.047278,-0.570187,-0.929397,-0.734539,-0.679063,1.517692,1.804941,1.222962,1
145,-0.069433,0.047278,-0.570187,2.532024,-0.734539,-0.679063,-0.805741,-0.554035,-1.406286,1
131,0.312459,1.403419,-0.570187,2.532024,-0.734539,-0.679063,-0.805741,-0.554035,-0.091662,1
239,-0.530656,0.047278,-0.570187,0.224410,-0.734539,-0.679063,0.355976,-0.554035,-1.406286,1
321,-0.701308,0.047278,1.421812,0.224410,-0.734539,-0.679063,1.517692,-0.554035,-0.091662,1
345,-1.446183,0.047278,-0.570187,0.224410,1.361397,-0.679063,-0.805741,1.804941,-0.091662,1
32,-0.124780,1.403419,1.421812,0.224410,-0.734539,1.472618,0.355976,1.804941,-1.406286,1
313,-0.678247,0.047278,1.421812,0.224410,-0.734539,-0.679063,-0.805741,-0.554035,-0.091662,1
5,1.083624,0.047278,3.413810,-0.929397,1.361397,1.472618,1.517692,1.804941,-0.091662,1
534,-0.991879,1.403419,-0.570187,0.224410,-0.734539,-0.679063,-0.805741,-0.554035,1.222962,1

In [ ]:
theta = [x*0.1 for x in range(len(X.columns))]
theta

[0.0,
 0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6000000000000001,
 0.7000000000000001,
 0.8,
 0.9]

In [ ]:
from ctypes import Array
J_prev = float('inf')
tolerance = 1e-20
itr = 0
# print(theta0,theta1)


while True :
    itr+=1
    y_cap = theta0 + theta1 * X


    J = ((y_cap - Y) ** 2).sum() / (2 * m)

    if abs(J_prev - J) < tolerance or itr >= 1000:
        break

    deltaJ0 = (y_cap - Y).sum() / m
    deltaJ1 = ((y_cap - Y) * X).sum() / m

    t0 = theta0 - alpha * deltaJ0
    t1 = theta1 - alpha * deltaJ1

    theta0 = t0
    theta1 = t1

    J_prev = J

theta0, theta1, itr

NameError: name 'xlabel' is not defined